import { Geist, Geist_Mono, Lobster_Two, Delius_Swash_Caps } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lobsterTwo = Lobster_Two({
  variable: "--font-lobster-two",
  subsets: ["latin"],
  weight: ["400", "700"], 
  style: ["normal", "italic"],
});

const delius = Delius_Swash_Caps({
  variable: "--font-delius",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${delius.variable} ${geistSans.variable} ${geistMono.variable} ${lobsterTwo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
